# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c710c747ca258d6c2d939b69e38e3c78bb8ed4c6049f485c4714799188928d1ecae253425113494bad40906342c991857597b618dfcc37cb2434533b66d783f

test:
  secret_key_base: 8b48fde26a42fbdb8adc4bcb9666ab8cb88b975d0e92b0d15e875885f63442e54ea100442bf0babe1d94a5df58bb69f6a838aadadfbe35e57881b607194d01f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
